server.port: 8762
spring:
  application:
    name:
      SPRING-GATEWAY
    instance:
      preferIpAddress: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway