spring:
  datasource:
    url: "jdbc:postgresql://categories "
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name:
      COMMON-API-CATEGORY
  eureka:
    client:
      serviceUrl:
        defaultZone:
          http://common-eureka-spring/eureka/
    instance:
      preferIpAddress: true
api:
  config:
    defaultPageSize:
      30
    maxPageSize:
      60