spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: COMMON-API-OPERATION
  datasource:
    url: "jdbc:postgresql://postgres/finasist"

#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://common-eureka-spring:8761/eureka/
#    instance:
#      preferIpAddress: true
